/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FindRouteImport } from './routes/find'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmergencyRouteImport } from './routes/_authenticated/emergency'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedItineraryRouteImport } from './routes/_authenticated/itinerary'
import { Route as AuthenticatedLiveTrackingRouteImport } from './routes/_authenticated/live-tracking'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedSafetyTagsRouteImport } from './routes/_authenticated/safety-tags'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as TTokenRouteImport } from './routes/t.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmergencyRoute = AuthenticatedEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItineraryRoute = AuthenticatedItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveTrackingRoute =
  AuthenticatedLiveTrackingRouteImport.update({
    id: '/live-tracking',
    path: '/live-tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyTagsRoute = AuthenticatedSafetyTagsRouteImport.update({
  id: '/safety-tags',
  path: '/safety-tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TTokenRoute = TTokenRouteImport.update({
  id: '/t/$token',
  path: '/t/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find': typeof FindRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/itinerary': typeof AuthenticatedItineraryRoute
  '/live-tracking': typeof AuthenticatedLiveTrackingRoute
  '/map': typeof AuthenticatedMapRoute
  '/safety-tags': typeof AuthenticatedSafetyTagsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/t/$token': typeof TTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find': typeof FindRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/emergency': typeof AuthenticatedEmergencyRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/itinerary': typeof AuthenticatedItineraryRoute
  '/live-tracking': typeof AuthenticatedLiveTrackingRoute
  '/map': typeof AuthenticatedMapRoute
  '/safety-tags': typeof AuthenticatedSafetyTagsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/t/$token': typeof TTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/find': typeof FindRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/emergency': typeof AuthenticatedEmergencyRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/itinerary': typeof AuthenticatedItineraryRoute
  '/_authenticated/live-tracking': typeof AuthenticatedLiveTrackingRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/safety-tags': typeof AuthenticatedSafetyTagsRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/t/$token': typeof TTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/find'
    | '/dashboard'
    | '/emergency'
    | '/explore'
    | '/itinerary'
    | '/live-tracking'
    | '/map'
    | '/safety-tags'
    | '/setup'
    | '/t/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/find'
    | '/dashboard'
    | '/emergency'
    | '/explore'
    | '/itinerary'
    | '/live-tracking'
    | '/map'
    | '/safety-tags'
    | '/setup'
    | '/t/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/find'
    | '/_authenticated/dashboard'
    | '/_authenticated/emergency'
    | '/_authenticated/explore'
    | '/_authenticated/itinerary'
    | '/_authenticated/live-tracking'
    | '/_authenticated/map'
    | '/_authenticated/safety-tags'
    | '/_authenticated/setup'
    | '/t/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FindRoute: typeof FindRoute
  TTokenRoute: typeof TTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emergency': {
      id: '/_authenticated/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof AuthenticatedEmergencyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itinerary': {
      id: '/_authenticated/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof AuthenticatedItineraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-tracking': {
      id: '/_authenticated/live-tracking'
      path: '/live-tracking'
      fullPath: '/live-tracking'
      preLoaderRoute: typeof AuthenticatedLiveTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety-tags': {
      id: '/_authenticated/safety-tags'
      path: '/safety-tags'
      fullPath: '/safety-tags'
      preLoaderRoute: typeof AuthenticatedSafetyTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/t/$token': {
      id: '/t/$token'
      path: '/t/$token'
      fullPath: '/t/$token'
      preLoaderRoute: typeof TTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmergencyRoute: typeof AuthenticatedEmergencyRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedItineraryRoute: typeof AuthenticatedItineraryRoute
  AuthenticatedLiveTrackingRoute: typeof AuthenticatedLiveTrackingRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedSafetyTagsRoute: typeof AuthenticatedSafetyTagsRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmergencyRoute: AuthenticatedEmergencyRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedItineraryRoute: AuthenticatedItineraryRoute,
  AuthenticatedLiveTrackingRoute: AuthenticatedLiveTrackingRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedSafetyTagsRoute: AuthenticatedSafetyTagsRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FindRoute: FindRoute,
  TTokenRoute: TTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
